### ISSUE TITLE
Dropdown entries invisible

### ISSUE THREAD

**Issue by garyemerson** [hanford/trends#3]
Cool project! Small UI hiccup, looks like all but the selected entry in both dropdowns is invisible:

![screencap](https://user-images.githubusercontent.com/5726308/43162566-4c767d2e-8f40-11e8-9084-c2f549f31d12.png)

This is on Chrome Version 67.0.3396.99 (Official Build) (64-bit) and Windows 10.0.17134 Build 17134

**Comment by hanford** [comment]
this should be fixed now do to this commit https://github.com/hanford/trends/commit/36a17eed3ad119252beb1f4b11d95ad3df1e625f, I don't have windows to verify .. could you do a hard refresh and let me know?

**Comment by garyemerson** [comment]
Yep, looks good. Thanks for the quick fix!

![screencap](https://user-images.githubusercontent.com/5726308/43172272-6e10c264-8f63-11e8-8bb9-782a3dc2dcc2.png)
