### ISSUE TITLE
Dropdowns render with white text and white background

### ISSUE THREAD

**Issue by coltonhurst** [hanford/trends#4]
Great site! I found it via HN.

Submitting an "issue", more of an FYI... but if it was just a side project and you don't care then it's all good 👍 

On Firefox on OS X, the dropdowns render with white text and a white background. Unless I hover with the mouse pointer and the selection becomes blue, I can't see the text.

<img width="379" alt="dropdown" src="https://user-images.githubusercontent.com/5691612/43162808-340aa07a-8f5a-11e8-9614-24f843fb4bc3.png">

**Comment by hanford** [comment]
this should be fixed now, you may need to hard refresh!

**Comment by coltonhurst** [comment]
Seems like this issue and the equivalent one were reported around the same time, I didn't see the other issue until after I had finished typing mine.

Thanks for fixing!
