### ISSUE TITLE
Rate limit exceeded

### ISSUE THREAD

**Issue by Jarred-Sumner** [hanford/trends#47]
![539D1C7C-7336-4818-990D-B4BC05F401BA](https://user-images.githubusercontent.com/709451/103445827-b5aa2c80-4c2d-11eb-87ee-6fe38d46059b.png)

**Comment by hanford** [comment]
Seems to be working now, not entirely sure what happened ...

I changed a bunch of application code, but it seemed like a secrets/api token thing between trends/github/vercel
